default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_capstone_development
  user: pgsv_user
  password: pgsv_pw

test:
  <<: *default
  database: Rails_Budget_App_test
  user: postgres
  password: password

production:
  <<: *default
  database: rails_capstone_production
  username: rails_capstone
  password: <%= ENV["RAILS_CAPSTONE_DATABASE_PASSWORD"] %>
