default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_capstone_development
  user: pgsv_user
  password: pgsv_pw

test:
  <<: *default
  database: rails_capstone_test
  user: pgsv_user
  password: pgsv_pw

production:
  url: <%= ENV['DATABASE_URL'] %>
